# Copyright 2026 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable desktop tauri build workflow"

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: ""
      tagName:
        required: false
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            symbol: ğŸ§
            platform: Linux
          - os: "ubuntu-latest"
            symbol: ğŸ§
            platform: Linux
            target: aarch64-unknown-linux-gnu
            dependencies: |
              sudo apt-get update
              sudo apt-get -y install gcc-aarch64-linux-gnu
          - os: "ubuntu-latest"
            symbol: ğŸ§
            platform: Linux
            target: arm-unknown-linux-gnueabihf
            dependencies: |
              sudo apt-get update
              sudo apt-get -y install gcc-13-arm-linux-gnueabihf
          - os: "macos-latest"
            target: aarch64-apple-darwin
            symbol: ğŸ
            platform: macOS
          - os: "macos-latest"
            target: x86_64-apple-darwin
            symbol: ğŸ
            platform: macOS
          - os: "windows-latest"
            symbol: ğŸªŸ
            platform: Windows

    name: ${{matrix.symbol}}ğŸ”¨
    runs-on: ${{matrix.os}}
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ¦€ğŸš€
        uses: ./.github/actions/setup-rust-cache
        with:
          targets: ${{ matrix.target || '' }}
          save-cache: ${{ inputs.branch == 'main' }}

      - name: ğŸ› ï¸ dependencies
        if: matrix.dependencies
        shell: bash
        run: |
          ${{ matrix.dependencies }}

      - name: ğŸ› ï¸ğŸš€
        if: (!inputs.tagName)
        uses: ./.github/actions/setup-sccache

      - name: ğŸ”¨ Build
        shell: bash
        env:
          RUSTFLAGS: "-D warnings"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release
          fi

      - name: ğŸ“¦ Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: mdns-tui-browser-${{ matrix.platform }}${{ matrix.target && '-' || '' }}${{ matrix.target || '' }}
          path: |
            target/${{ matrix.target && format('{0}/', matrix.target) || '' }}release/mdns-tui-browser
            target/${{ matrix.target && format('{0}/', matrix.target) || '' }}release/mdns-tui-browser.exe
          retention-days: 30
