# Copyright 2025 hrzlgnm
# SPDX-License-Identifier: MIT-0

name: "Reusable ci lint workflow"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ¦€ğŸš€
        uses: ./.github/actions/setup-rust-cache
        with:
          components: rustfmt

      - name: ğŸ“ Run rustfmt and fail if any warnings
        shell: bash
        run: |
          cargo fmt -- --check

  clippy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            symbol: ğŸ§
            platform: Linux
          - os: "macos-latest"
            symbol: ğŸ
          - os: "windows-latest"
            symbol: ğŸªŸ
    runs-on: ${{matrix.os}}
    name: ${{matrix.symbol}}ğŸ“
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ğŸ¦€ğŸš€
        uses: ./.github/actions/setup-rust-cache
        with:
          components: clippy
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: ğŸ› ï¸ğŸš€
        uses: ./.github/actions/setup-sccache

      - name: ğŸ“ Run clippy and fail if any warnings
        shell: bash
        run: |
          cargo clippy -- -D warnings
